### ISSUE TITLE
Google アナリティクス利用に関する情報開示がされていない

### ISSUE THREAD

**Issue by masuP9** [freee/a11y-guidelines#12]
ウェブページ上では Google アナリティクスを利用していると思われますが、Google アナリティクス利用規約によると

> プライバシー ポリシーを公開し、そのプライバシー ポリシーで Cookie の使用、モバイル デバイスの識別情報（Android の広告識別子、iOS の広告識別子など）、またはデータの収集に使われる類似の技術について必ず通知するものとします。また、Google アナリティクスを使用していること、および Google アナリティクスでデータが収集、処理される仕組みについても開示する必要があります。こうした情報を開示するには、「ユーザーが Google パートナーのサイトやアプリを使用する際の Google によるデータ使用」のページ（www.google.com/intl/ja/policies/privacy/partners/ または Google が随時提供するその他の URL）へのリンクを⽬立つように表示します。お客様は、本サービスに関連してユーザーのデバイス上で Cookie やその他の情報を保存、アクセスする行為が発生し、かかる行為に関する情報の提供とユーザーからの同意が必要であると法律で定められている場合には、ユーザーに明確かつ包括的な情報を提供し、同意を得るための商業上合理的な努力を払うものとします。

[Terms of Service \| Google Analytics – Google](https://marketingplatform.google.com/about/analytics/terms/jp/)

とあるので、なにかしら記載をしたほうが良さそうです。

**Comment by ma10** [comment]
少し時間がかかってしまいましたが、 <https://a11y-guidelines.freee.co.jp/> に公開するものについては、各ページのフッターにGoogle Analytics使用について表示するように変更しました。

ご指摘ありがとうございました。
