### ISSUE TITLE
誤字と思われる表現の報告：「見足している」→「満たしている」

### ISSUE THREAD

**Issue by taigakiyokawa** [freee/a11y-guidelines#151]
（急ぎではないです）

いつも大変参考にさせていただいております。

当ガイドラインにて誤字と思われる表現が複数箇所で使用されているのを発見したので報告いたします。当ガイドラインの特にチェック方法のいくつかの記述において「見足している」という表現が使用されていますが、こちらは以下の根拠から「満たしている」の誤字ではないかと思いました。もし誤字ではなく意図的に「見足している」という表現を使用している場合、よろしければ「満たしている」との違いを教えていただきたいです。

- 予測変換（Google日本語入力）にて候補として出てこない
- Google検索にて「"見足す"」や「"見足している"」のヒット件数がごくわずか（"見足している"の場合、約5件）であり、辞書系のサイトでの解説がヒットしない
- ガイドライン上で「満たしている」と「見足している」が混在している

例：https://a11y-guidelines.freee.co.jp/checks/checklist.html#check-0561 の「チェック手順：Web」にて

> 以下のaxe DevToolsによるチェックを満たしていて、かつNVDAによるチェックまたはmacOS VoiceOverによるチェックのいずれかを見足していることを確認する。

（ほか、https://a11y-guidelines.freee.co.jp/checks/checklist.html を「見足している」でページ内検索した結果、30箇所を検出しました）

**Comment by ma10** [comment]
ご指摘ありがとうございます。
単純な誤字だと思われますので、次回リリース時に修正できるようにします。

**Comment by ma10** [comment]
#152 で修正完了しました。
