### ISSUE TITLE
ブログのfreeeアクセシビリティー・ガイドラインへのリンクを修正してください

### ISSUE THREAD

**Issue by nanami-nanami** [freee/a11y-guidelines#16]
該当ブログ
https://developers.freee.co.jp/entry/a11y-guidelines-202201.0

リンク元
freeeアクセシビリティー・ガイドライン

現在のリンク（間違ったリンク）
https://a11y-guidelines.free.co.jp/

理想のリンク
https://a11y-guidelines.freee.co.jp/

**Comment by ma10** [comment]
ご指摘ありがとうございます。
修正しました。
