### ISSUE TITLE
[表記ルール] 単位付き数値の前後の空白ルールの不統一

### ISSUE THREAD

**Issue by kotarok** [freee/a11y-guidelines#7]
# 概要
単位付き数値の表記において、その前後に空白を設けるか否かのルールが不統一であるように見えます。

# 該当箇所
例えばこれらのページ
- https://a11y-guidelines.freee.co.jp/categories/login_session.html
- https://a11y-guidelines.freee.co.jp/categories/form.html
- https://a11y-guidelines.freee.co.jp/categories/dynamic_content.html
他にもあるかも知れない

# 具体的な不具合内容
以下のようにルールが揺れている
数値の前にのみ空白: `設定の 10倍`, `少なくとも 20秒間`
数値の後にのみ空白: `を10 回`, `20 時間`
数値の前後に空白: `制限時間が 20 時間`, `(2) 5 秒より`
空白なし: `(1)自動的に`

# 望ましい状態
- ルールが制定され、一貫した表記に改められる
- README などにそのルールが示される

**Comment by ma10** [comment]
ご指摘ありがとうございます。

[JTF日本語標準スタイルガイド(翻訳用）](https://www.jtf.jp/jp/style_guide/styleguide_top.html)に基づいて表記を統一することとし、先ほどリリースした[Ver. 202005.1](https://github.com/freee/a11y-guidelines/releases/tag/202005.1)で反映しました。

また、READMEにもその旨記載しました。
