### ISSUE TITLE
Detailsを開くと項目親子関係が分かりづらくなる。

### ISSUE THREAD

**Issue by naoya7076** [freee/a11y-guidelines#8]
例えば[こちらのサイト](https://a11y-guidelines.freee.co.jp/categories/markup.html)の場合、Detailsを開く前は
- [MUST] セマンティクスを表す適切な要素を用いる。
- [MUST] 仕様に準拠したマークアップを行う。
の区切りが分かりやすいです。
![image](https://user-images.githubusercontent.com/32981554/82675326-a0285980-9c7f-11ea-8479-468b39aaff30.png)

しかし、Detailを開くと、大きな項目である
- [MUST] セマンティクスを表す適切な要素を用いる。
- [MUST] 仕様に準拠したマークアップを行う。
よりも、子項目である
- 意図
- チェック内容
などの項目のほうが視覚的に目立つため、項目の親子関係が分かりづらくなっていると感じます。
![image](https://user-images.githubusercontent.com/32981554/82675620-0ca35880-9c80-11ea-9c3a-8995f087f1d1.png)

**Comment by ma10** [comment]
@naoya7076 ご指摘ありがとうございます。

ガイドラインの文書構成を見直したものを先日リリースし、ご指摘の問題も改善したかと思うのですがいかがでしょうか。

**Comment by naoya7076** [comment]
ご連絡ありがとうございますー！かなり親子関係が見やすくなりましたー
